apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: todo-user-db
  name: todo-user-db-dep
  namespace: todo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: todo-user-db
    spec:
      containers:
      - image: mongo
        name: todo-user-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: todo-user-db-mongodata
      restartPolicy: Always
      volumes:
      - name: todo-user-db-mongodata
        persistentVolumeClaim:
          claimName: todo-user-db-mongodata
status: {}
